Repository woowa-techcamp-2021/baemin-10, pull requests merged in 2021-07, with the labels that each got.

#24 Feature: 메인화면 레이아웃 구조화 (#7)
  baemin-register/public/stylesheets/index.css
  baemin-register/public/stylesheets/mobile.css
  baemin-register/public/stylesheets/reset.css
  baemin-register/public/stylesheets/style.css
  baemin-register/views/index.ejs
Labels: FE

#25 [Markup] 로그인 페이지 구현하기 #8
  baemin-register/public/stylesheets/login.css
  baemin-register/public/stylesheets/reset.css
  baemin-register/views/auth/login.ejs
Labels: FE

#30 Feature: 회원가입 상세정보 화면 마크업(#11)
  baemin-register/public/stylesheets/mobile.css
  baemin-register/public/stylesheets/registerDetail.css
  baemin-register/views/auth/registerDetail.ejs
Labels: FE

#31 Feature: 회원가입-휴대전화 입력 화면 마크업(#10)
  baemin-register/public/stylesheets/registerPhone.css
  baemin-register/views/auth/registerPhone.ejs
Labels: FE

#32 Update: viewport 메타 태그 추가(#7, #28)
  baemin-register/views/index.ejs
Labels: FE

#33 [Markup] 가입 약관 동의 - 페이지 레이아웃 구성
  baemin-register/public/assets/images/checkbox_F.png
  baemin-register/public/assets/images/checkbox_T.png
  baemin-register/public/javascripts/registerTerms/index.js
  baemin-register/public/stylesheets/login.css
  baemin-register/public/stylesheets/registerTerms.css
  baemin-register/views/auth/login.ejs
  baemin-register/views/auth/registerTerms.ejs
Labels: FE

#35 [Feature] 로그인 화면 기능 구현
  baemin-register/public/javascripts/login/index.js
  baemin-register/public/stylesheets/login.css
  baemin-register/views/auth/login.ejs
Labels: FE

#36 [Feature] 가입-약관동의 화면 기능 구현 #14
  baemin-register/app.js
  baemin-register/public/javascripts/login/index.js
  baemin-register/public/javascripts/registerTerms/index.js
  baemin-register/public/javascripts/utils/eventHelper.js
  baemin-register/public/stylesheets/registerTerms.css
  baemin-register/routes/auth.js
  baemin-register/views/auth/registerTerms.ejs
Labels: FE

#37 [Feature] 회원가입 휴대전화 입력 기능 구현 #15
  baemin-register/public/javascripts/registerPhone/index.js
  baemin-register/public/javascripts/utils/checkRegex.js
  baemin-register/public/stylesheets/common/reset.css
  baemin-register/public/stylesheets/registerPhone.css
  baemin-register/views/auth/registerPhone.ejs
Labels: FE

#39 [Feature] 세부정보 입력 화면 기능구현 #16
  baemin-register/public/javascripts/registerDetail/index.js
  baemin-register/public/javascripts/utils/checkRegex.js
  baemin-register/public/stylesheets/registerDetail.css
  baemin-register/views/auth/registerDetail.ejs
Labels: FE

#42 BUGFIX: 휴대전화번호 검증 실패 버그 해결
  baemin-register/public/javascripts/registerPhone/index.js
  baemin-register/public/javascripts/utils/checkRegex.js
  baemin-register/views/auth/registerPhone.ejs
Labels: bug

#43 Update: 회원가입 상세정보 입력화면 수정 (#16)
  baemin-register/public/javascripts/registerDetail/index.js
  baemin-register/views/auth/registerDetail.ejs
Labels: FE

#44 Feature: 메인화면 서버 연동
  baemin-register/public/stylesheets/index.css
  baemin-register/routes/index.js
  baemin-register/views/index.ejs
Labels: BE

#45 Feature: 가입-약관 동의 화면 서버 로직 구현
  baemin-register/models/account/sqlite/SQLITE3AccountStore.js
  baemin-register/models/register/RegisterInfo.js
  baemin-register/public/stylesheets/registerTerms.css
  baemin-register/routes/auth.js
  baemin-register/routes/index.js
  baemin-register/views/auth/login.ejs
  baemin-register/views/auth/registerTerms.ejs
Labels: BE

#48 Update: 백엔드 폴더 구조 정리 및 회원가입 휴대전화 번호 입력화면 서버 연동
  baemin-register/app.js
  baemin-register/public/stylesheets/registerPhone.css
  baemin-register/routes/api/check/email/index.js
  baemin-register/routes/api/check/index.js
  baemin-register/routes/api/index.js
  baemin-register/routes/auth.js
  baemin-register/routes/auth/index.js
  baemin-register/routes/auth/login.js
  baemin-register/routes/auth/registerDetail.js
  baemin-register/routes/auth/registerPhone.js
  baemin-register/routes/auth/registerTerms.js
  baemin-register/routes/index.js
  baemin-register/views/auth/registerPhone.ejs
Labels: BE

#51 Feature: 회원가입 상세정보 입력화면 서버 연동 (#21, #22)
  baemin-register/public/javascripts/registerDetail/index.js
  baemin-register/public/stylesheets/registerDetail.css
  baemin-register/routes/api/account/id/index.js
  baemin-register/routes/api/account/index.js
  baemin-register/routes/api/check/email/index.js
  baemin-register/routes/api/index.js
  baemin-register/routes/auth/registerDetail.js
  baemin-register/routes/auth/registerPhone.js
  baemin-register/views/auth/registerDetail.ejs
Labels: BE

#55 Update: 전화번호, 생년월일 숫자외 입력 불가 기능 추가
  public/javascripts/registerDetail/index.js
  public/javascripts/registerPhone/index.js
  public/javascripts/utils/checkRegex.js
Labels: FE

#59 Update: UI 코드 맞추기
  public/stylesheets/common/mobile.css
  public/stylesheets/index.css
  public/stylesheets/login.css
  public/stylesheets/registerDetail.css
  public/stylesheets/registerPhone.css
  public/stylesheets/registerTerms.css
  views/auth/login.ejs
  views/auth/registerTerms.ejs
  views/index.ejs
Labels: FE
